export const NBATeams = [
    { value: "1", label: "Atlanta Hawks"},
    { value: "2", label: "Boston Celtics"},
    { value: "4", label: "Brooklyn Nets"},
    { value: "5", label: "Charlotte Hornets"},
    { value: "6", label: "Chicago Bulls"},
    { value: "7", label: "Cleveland Cavaliers"},
    { value: "8", label: "Dallas Mavericks"},
    { value: "9", label: "Denver Nuggets"},
    { value: "10", label: "Detroit Pistons"},
    { value: "11", label: "Golden State Warriors"},
    { value: "14", label: "Houston Rockets"},
    { value: "15", label: "Indiana Pacers"},
    { value: "16", label: "Los Angeles Clippers"},
    { value: "17", label: "Los Angeles Lakers"},
    { value: "19", label: "Memphis Grizzlies"},
    { value: "20", label: "Miami Heat"},
    { value: "21", label: "Milwaukee Bucks"},
    { value: "22", label: "Minnesota Timberwolves"},
    { value: "23", label: "New Orleans Pelicans"},
    { value: "24", label: "New York Knicks"},
    { value: "25", label: "Oklahoma City Thunder"},
    { value: "26", label: "Orlando Magic"},
    { value: "27", label: "Philadelphia 76ers"},
    { value: "28", label: "Phoenix Suns"},
    { value: "29", label: "Portland Trail Blazers"},
    { value: "30", label: "Sacramento Kings"},
    { value: "31", label: "San Antonio Spurs"},
    // { value: "34", label: "Team Durant"},
    // { value: "35", label: "Team LeBron"},
    // { value: "1413", label: "Team USA"},
    // { value: "1414", label: "Team World"},
    { value: "38", label: "Toronto Raptors"},
    { value: "40", label: "Utah Jazz"},
    { value: "41", label: "Washington Wizards"},
  ];