export const NBATeams = [
  { value: "1", label: "Atlanta Hawks" },
  { value: "2", label: "Boston Celtics" },
  { value: "4", label: "Brooklyn Nets" },
  { value: "5", label: "Charlotte Hornets" },
  { value: "6", label: "Chicago Bulls" },
  { value: "7", label: "Cleveland Cavaliers" },
  { value: "8", label: "Dallas Mavericks" },
  { value: "9", label: "Denver Nuggets" },
  { value: "10", label: "Detroit Pistons" },
  { value: "11", label: "Golden State Warriors" },
  { value: "14", label: "Houston Rockets" },
  { value: "15", label: "Indiana Pacers" },
  { value: "16", label: "Los Angeles Clippers" },
  { value: "17", label: "Los Angeles Lakers" },
  { value: "19", label: "Memphis Grizzlies" },
  { value: "20", label: "Miami Heat" },
  { value: "21", label: "Milwaukee Bucks" },
  { value: "22", label: "Minnesota Timberwolves" },
  { value: "23", label: "New Orleans Pelicans" },
  { value: "24", label: "New York Knicks" },
  { value: "25", label: "Oklahoma City Thunder" },
  { value: "26", label: "Orlando Magic" },
  { value: "27", label: "Philadelphia 76ers" },
  { value: "28", label: "Phoenix Suns" },
  { value: "29", label: "Portland Trail Blazers" },
  { value: "30", label: "Sacramento Kings" },
  { value: "31", label: "San Antonio Spurs" },
  // { value: "34", label: "Team Durant"},
  // { value: "35", label: "Team LeBron"},
  // { value: "1413", label: "Team USA"},
  // { value: "1414", label: "Team World"},
  { value: "38", label: "Toronto Raptors" },
  { value: "40", label: "Utah Jazz" },
  { value: "41", label: "Washington Wizards" },
];

export const F1Teams = [
  { value: "1", label: "Red Bull Racing" },
  { value: "2", label: "McLaren Racing" },
  { value: "3", label: "Scuderia Ferrari" },
  //{ value: "4", label: "Force India" },
  { value: "5", label: "Mercedes-AMG Petronas" },
  //{ value: "6", label: "Lotus F1 Team" },
  { value: "7", label: "Scuderia AlphaTauri Honda" },
  //{ value: "8", label: "Sauber F1 Team" },
  //{ value: "9", label: "Manor Marussia F1 Team" },
  //{ value: "10", label: "Caterham F1 Team" },
  //{ value: "11", label: "HRT Formula One Team" },
  { value: "12", label: "Williams F1 Team" },
  { value: "13", label: "Alpine F1 Team" },
  { value: "14", label: "Haas F1 Team" },
  //{ value: "15", label: "Virgin Racing" },
  //{ value: "16", label: "Manor Racing" },
  { value: "17", label: "Aston Martin F1 Team" },
  { value: "18", label: "Alfa Romeo" },
];

export const SearchOptions = [
  { id: "r1", label: "Red Bull Racing" },
  { id: "r2", label: "McLaren Racing" },
  { id: "r3", label: "Scuderia Ferrari" },
  //{ id: "r4", label: "Force India" },
  { id: "r5", label: "Mercedes-AMG Petronas" },
  //{ id: "r6", label: "Lotus F1 Team" },
  { id: "r7", label: "Scuderia AlphaTauri Honda" },
  //{ id: "r8", label: "Sauber F1 Team" },
  //{ id: "r9", label: "Manor Marussia F1 Team" },
  //{ id: "r10", label: "Caterham F1 Team" },
  //{ id: "r11", label: "HRT Formula One Team" },
  { id: "r12", label: "Williams F1 Team" },
  { id: "r13", label: "Alpine F1 Team" },
  { id: "r14", label: "Haas F1 Team" },
  //{ id: "r15", label: "Virgin Racing" },
  //{ id: "r16", label: "Manor Racing" },
  { id: "r17", label: "Aston Martin F1 Team" },
  { id: "r18", label: "Alfa Romeo" },
  
  { id: "g1", label: "Atlanta Hawks" },
  { id: "g2", label: "Boston Celtics" },
  { id: "g4", label: "Brooklyn Nets" },
  { id: "g5", label: "Charlotte Hornets" },
  { id: "g6", label: "Chicago Bulls" },
  { id: "g7", label: "Cleveland Cavaliers" },
  { id: "g8", label: "Dallas Mavericks" },
  { id: "g9", label: "Denver Nuggets" },
  { id: "g10", label: "Detroit Pistons" },
  { id: "g11", label: "Golden State Warriors" },
  { id: "g14", label: "Houston Rockets" },
  { id: "g15", label: "Indiana Pacers" },
  { id: "g16", label: "Los Angeles Clippers" },
  { id: "g17", label: "Los Angeles Lakers" },
  { id: "g19", label: "Memphis Grizzlies" },
  { id: "g20", label: "Miami Heat" },
  { id: "g21", label: "Milwaukee Bucks" },
  { id: "g22", label: "Minnesota Timberwolves" },
  { id: "g23", label: "New Orleans Pelicans" },
  { id: "g24", label: "New York Knicks" },
  { id: "g25", label: "Oklahoma City Thunder" },
  { id: "g26", label: "Orlando Magic" },
  { id: "g27", label: "Philadelphia 76ers" },
  { id: "g28", label: "Phoenix Suns" },
  { id: "g29", label: "Portland Trail Blazers" },
  { id: "g30", label: "Sacramento Kings" },
  { id: "g31", label: "San Antonio Spurs" },
  // { idg: "34", label: "Team Durant"},
  // { idg: "35", label: "Team LeBron"},
  // { idg: "1413", label: "Team USA"},
  // { idg: "1414", label: "Team World"},
  { id: "g38", label: "Toronto Raptors" },
  { id: "g40", label: "Utah Jazz" },
  { id: "g41", label: "Washington Wizards" },
];

export const SeasonOptions = [
  { id: "2019", label: "2019/2020" },
  { id: "2020", label: "2020/2021" },
]