export const NBATeams = [
    { value: "132", label: "Atlanta Hawks"},
    { value: "133", label: "Boston Celtics"},
    { value: "134", label: "Brooklyn Nets"},
    { value: "135", label: "Charlotte Hornets"},
    { value: "136", label: "Chicago Bulls"},
    { value: "137", label: "Cleveland Cavaliers"},
    { value: "138", label: "Dallas Mavericks"},
    { value: "139", label: "Denver Nuggets"},
    { value: "140", label: "Detroit Pistons"},
    { value: "141", label: "Golden State Warriors"},
    { value: "142", label: "Houston Rockets"},
    { value: "143", label: "Indiana Pacers"},
    { value: "144", label: "Los Angeles Clippers"},
    { value: "145", label: "Los Angeles Lakers"},
    { value: "146", label: "Memphis Grizzlies"},
    { value: "147", label: "Miami Heat"},
    { value: "148", label: "Milwaukee Bucks"},
    { value: "149", label: "Minnesota Timberwolves"},
    { value: "150", label: "New Orleans Pelicans"},
    { value: "151", label: "New York Knicks"},
    { value: "152", label: "Oklahoma City Thunder"},
    { value: "153", label: "Orlando Magic"},
    { value: "154", label: "Philadelphia 76ers"},
    { value: "155", label: "Phoenix Suns"},
    { value: "156", label: "Portland Trail Blazers"},
    { value: "157", label: "Sacramento Kings"},
    { value: "158", label: "San Antonio Spurs"},
    { value: "1411", label: "Team Giannis"},
    { value: "1412", label: "Team LeBron"},
    { value: "1413", label: "Team USA"},
    { value: "1414", label: "Team World"},
    { value: "159", label: "Toronto Raptors"},
    { value: "160", label: "Utah Jazz"},
    { value: "161", label: "Washington Wizards"},
  ];